services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: umwix1002
    restart: always
    ports:
      - 3307:3306
    volumes:
      - my-db-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  my-db-volume: